### ISSUE TITLE
BookState

### ISSUE THREAD

**Issue by nassimbjf** [lohanidamodar/flutter_audiobooks_app#1]
WHY THIS FUNCTION IS UNDERLINED BY RED COLOR 
  @override
  Stream<BookState> mapEventToState(currentState, event) async* {
    if (event is FetchBook && !_hasReachedMax(currentState)) {
      try {
        if (currentState is BookUninitialized) {
          final books = await _fetchBooks(0, 20);
          yield BookInitialized.success(books);
        }
        if (currentState is BookInitialized) {
          final books = await _fetchBooks(currentState.books.length, 20);
          yield books.isEmpty
              ? currentState.copyWith(hasReachedMax: true)
              : BookInitialized.success(currentState.books + books);
        }
      } catch (_) {
        yield BookInitialized.failure();
      }
    }
  }

**Comment by lohanidamodar** [comment]
Also paste the output of your flutter doctor command! May be issue with dart version?
