### ISSUE TITLE
"no posts" at homepage when ran the code in as is state

### ISSUE THREAD

**Issue by srijan14** [lohanidamodar/flutter_audiobooks_app#6]
Getting "no posts" on home screen and nothing else(not section and anything) when running the code on Android emulator. Is there anything that needs to be changes for it to run as per the state mentioned in screenshots?

**Comment by lohanidamodar** [comment]
Should work automatically if you are connected to internet.

**Comment by lohanidamodar** [comment]
@srijan14 
Check if your debug console is giving any error and post the output

**Comment by srijan14** [comment]
@lohanidamodar Thanks for your suggestions. Actually your first interpretation was right, for some reason internet in my android emulator was not working. Debugged it and it worked as expected.
