### ISSUE TITLE
The playerService does not have a slider and player evolution.

### ISSUE THREAD

**Issue by gabihtoledo0** [lohanidamodar/flutter_audiobooks_app#8]
Hi, I have a question about this file. In the images of the readme it shows the player with a slider, but here in the code when running I don't see it. Were there changes?

https://github.com/lohanidamodar/flutter_audiobooks_app/blob/d0e6f59fbac38aa4f3feb1efb3f3cc1167518cd9/lib/pages/book_details.dart#L148

**Comment by lohanidamodar** [comment]
@gabihtoledo0 hey, sorry I've not updated it for a long time, may be some changes in plugins affected it. I'm not sure.

**Comment by lohanidamodar** [comment]
Latest version should now have all features, and supports Flutter 3
